---

<% if (tools.indexOf("traefik") > -1) { %> 
 - name: Create Traefik service
   shell: >
           docker service create \
            --name traefik \
            --constraint=node.role==manager \
            --publish 80:80 --publish 8080:8080 \
            --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
            --network <%= appName %>-net \
            --network elk-net \
            traefik:v1.1.2 \
            --docker \
            --docker.swarmmode \
            --docker.domain=<%= appName %> \
            --docker.watch \
            --web
<% } %>            