- hosts: mitosis_managers[0]
  name: "** Mitosis k8s Master  **"
  become: yes
  become_user: root
  serial: 1
  vars:
    mitosis_home: /opt/mitosis
    manager_ip: 192.168.77.21
    worker_token : 2f1a31.00f66dec74fd53f3 
  roles:
    - mitosis-master

- hosts: mitosis_workers
  name: "** Mitosis k8s Worker **"
  gather_facts: false
  become: yes
  become_user: root
  serial: 1
  vars:
    mitosis_home: /opt/mitosis
    manager_ip: 192.168.77.21
    worker_token : 2f1a31.00f66dec74fd53f3 
  roles:
    - mitosis-worker
