---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar
  labels:
    name: sonar
  namespace: mitosis
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: sonar
    spec:
      containers:
      - name: sonar
        image: mitosis/sonarqube
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonar
  labels:
    name: sonar
  namespace: mitosis
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 9000
    targetPort: 9000
    nodePort: 30002
  selector: