---      

<% if (ownRegistry) { %>  
- name: "Create service sonarqube"
  shell: >
         docker service create \
           --name sonarqube \
           --label traefik.port=80 \
           --label traefik.frontend.rule=Host:sonarqube.<%= appName %> \
           --publish 9000:9000 \
           --network <%= appName %>-net \
           --replicas 2 \
           <%= docker_registry_repository_name %>/sonarqube:1.0.0
- name: "Create service artifactory"
  shell: >
         docker service create \
           --name artifactory \
           --label traefik.frontend.rule=Host:artifactory.<%= appName %> \
           --label traefik.port=80 \
           --publish 9999:8080 \
           --network <%= appName %>-net \
           --replicas 2 \
           <%= docker_registry_repository_name %>/artifactory:1.0.0

- name: "Create service jenkins master"
  shell: >
         docker service create \
           --name jenkins \
           --label traefik.port=80 \
           --label traefik.frontend.rule=Host:jenkins.<%= appName %> \
           --mount "type=bind,target=/var/run/docker.sock,src=/var/run/docker.sock" \
           --mount "type=bind,target=/usr/bin/docker,src=/usr/bin/docker" \
           --publish 50000:50000 \
           --publish 8082:8080 \
           --network <%= appName %>-net \
           --replicas 2 \
           <%= docker_registry_repository_name %>/jenkins:1.0.0
<% } %>         

<% if (!ownRegistry) { %>  
- name: "Create service sonarqube"
  shell: >
         docker service create \
           --name sonarqube \
           --label traefik.port=80 \
           --label traefik.frontend.rule=Host:sonarqube.<%= appName %> \
           --publish 9000:9000 \
           --network <%= appName %>-net \
           --replicas 2 \
           mitosis/sonarqube:1.0.0-alpha.0
- name: "Create service artifactory"
  shell: >
         docker service create \
           --name artifactory \
           --label traefik.port=80 \
           --label traefik.frontend.rule=Host:artifactory.<%= appName %> \
           --publish 9999:8080 \
           --network <%= appName %>-net \
           --replicas 2 \
           mitosis/artifactory:1.0.0-alpha.0
<% } %>  
<% if (!defaultMicroService && !ownRegistry) { %>
- name: "Create service jenkins master"
  shell: >
         docker service create \
           --name jenkins \
           --label traefik.port=80 \
           --label traefik.frontend.rule=Host:jenkins.<%= appName %> \
           --mount "type=bind,target=/var/run/docker.sock,src=/var/run/docker.sock" \
           --mount "type=bind,target=/usr/bin/docker,src=/usr/bin/docker" \
           --publish 50000:50000 \
           --publish 8082:8080 \
           --network <%= appName %>-net \
           --replicas 2 mitosis/jenkins:default1.0.0-alpha.0
<% } %>   
<% if (!ownRegistry && defaultMicroService) { %> 
- name: "Create service jenkins master"
  shell: >
         docker service create \
           --name jenkins \
           --label traefik.port=80 \
           --label traefik.frontend.rule=Host:jenkins.<%= appName %> \
           --mount "type=bind,target=/var/run/docker.sock,src=/var/run/docker.sock" \
           --mount "type=bind,target=/usr/bin/docker,src=/usr/bin/docker" \
           --publish 50000:50000 \
           --publish 8082:8080 \
           --network <%= appName %>-net \
           --replicas 2 mitosis/jenkins:1.0.0-alpha.0
<% } %>