---      

<% if (ownRegistry && tools.indexOf("sonarqube") > -1) { %>  
- name: "Create service sonarqube"
  shell: >
         docker service create \
           --name sonarqube \
           --log-driver gelf \
           --log-opt gelf-address=udp://{{ manager_ip }}:12201 \
           --label traefik.port=9000 \
           --label traefik.frontend.rule=Host:sonarqube.<%= appName %> \
           --publish 9000:9000 \
           --network <%= appName %>-net \
           --replicas 2 \
           --reserve-memory 50m \
           <%= docker_registry_repository_name %>/sonarqube:1.0.0
<% } %>   

<% if (ownRegistry && tools.indexOf("artifactory") > -1) { %>             
- name: "Create service artifactory"
  shell: >
         docker service create \
           --name artifactory \
           --log-driver gelf \
           --log-opt gelf-address=udp://{{ manager_ip }}:12201 \           
           --label traefik.frontend.rule=Host:artifactory.<%= appName %> \
           --label traefik.port=9999 \
           --publish 9999:8080 \
           --network <%= appName %>-net \
           --replicas 2 \
           --reserve-memory 50m \
           <%= docker_registry_repository_name %>/artifactory:1.0.0
<% } %>   

<% if (ownRegistry && tools.indexOf("jenkins") > -1) { %>  
- name: "Create service jenkins master"
  shell: >
         docker service create \
           --name jenkins \
           --log-driver gelf \
           --log-opt gelf-address=udp://{{ manager_ip }}:12201 \           
           --label traefik.port=8082 \
           --label traefik.frontend.rule=Host:jenkins.<%= appName %> \
           --mount "type=bind,target=/var/run/docker.sock,src=/var/run/docker.sock" \
           --mount "type=bind,target=/usr/bin/docker,src=/usr/bin/docker" \
           --publish 50000:50000 \
           --publish 8082:8080 \
           --network <%= appName %>-net \
           --replicas 2 \
           --reserve-memory 100m \
           <%= docker_registry_repository_name %>/jenkins:1.0.0
<% } %>         

<% if (!ownRegistry && tools.indexOf("sonarqube") > -1) { %>  
- name: "Create service sonarqube"
  shell: >
         docker service create \
           --name sonarqube \
           --log-driver gelf \
           --log-opt gelf-address=udp://{{ manager_ip }}:12201 \           
           --label traefik.port=9000 \
           --label traefik.frontend.rule=Host:sonarqube.<%= appName %> \
           --publish 9000:9000 \
           --network <%= appName %>-net \
           --replicas 2 \
           --reserve-memory 50m \
           mitosis/sonarqube:1.0.0-alpha.0
<% } %>     

<% if (!ownRegistry && tools.indexOf("artifactory") > -1) { %>                        
- name: "Create service artifactory"
  shell: >
         docker service create \
           --log-driver gelf \
           --log-opt gelf-address=udp://{{ manager_ip }}:12201 \         
           --name artifactory \
           --label traefik.port=9999 \
           --label traefik.frontend.rule=Host:artifactory.<%= appName %> \
           --publish 9999:8080 \
           --network <%= appName %>-net \
           --replicas 2 \
           --reserve-memory 50m \
           mitosis/artifactory:1.0.0-alpha.0
<% } %>  

<% if (!defaultMicroService && !ownRegistry && tools.indexOf("jenkins") > -1) { %>
- name: "Create service jenkins master"
  shell: >
         docker service create \
           --log-driver gelf \
           --log-opt gelf-address=udp://{{ manager_ip }}:12201 \         
           --name jenkins \
           --label traefik.port=8082 \
           --label traefik.frontend.rule=Host:jenkins.<%= appName %> \
           --mount "type=bind,target=/var/run/docker.sock,src=/var/run/docker.sock" \
           --mount "type=bind,target=/usr/bin/docker,src=/usr/bin/docker" \
           --publish 50000:50000 \
           --publish 8082:8080 \
           --network <%= appName %>-net \
           --reserve-memory 100m \
           --replicas 2 mitosis/jenkins:default1.0.0-alpha.0
<% } %>   
<% if (!ownRegistry && defaultMicroService && tools.indexOf("jenkins") > -1) { %> 
- name: "Create service jenkins master"
  shell: >
         docker service create \
           --log-driver gelf \
           --log-opt gelf-address=udp://{{ manager_ip }}:12201 \         
           --name jenkins \
           --label traefik.port=8082 \
           --label traefik.frontend.rule=Host:jenkins.<%= appName %> \
           --mount "type=bind,target=/var/run/docker.sock,src=/var/run/docker.sock" \
           --mount "type=bind,target=/usr/bin/docker,src=/usr/bin/docker" \
           --publish 50000:50000 \
           --publish 8082:8080 \
           --network <%= appName %>-net \
           --reserve-memory 100m \
           --replicas 2 mitosis/jenkins:1.0.0-alpha.0
<% } %>